In [1]:
import pandas as pd

## Data Collection of COVID 10K Dataset

In [2]:
encounters = '10k_synthea_covid19_csv\10k_synthea_covid19_csv\encounters.csv'
patients = '10k_synthea_covid19_csv\10k_synthea_covid19_csv\patients.csv'
conditions = '10k_synthea_covid19_csv\10k_synthea_covid19_csv\conditions.csv'
mediations = '10k_synthea_covid19_csv\10k_synthea_covid19_csv\medications.csv'
immunizations = '10k_synthea_covid19_csv\10k_synthea_covid19_csv\immunizations.csv'
careplans = '10k_synthea_covid19_csv\10k_synthea_covid19_csv\careplans.csv'
procedures = '10k_synthea_covid19_csv\10k_synthea_covid19_csv\procedures.csv'
observations = '10k_synthea_covid19_csv\10k_synthea_covid19_csv\observations.csv'

In [3]:
# Let's read the encounters file
encounters_df = pd.read_csv(r'10k_synthea_covid19_csv\10k_synthea_covid19_csv\encounters.csv')

In [4]:
encounters_df.head()

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,d5ee30a9-362f-429e-a87a-ee38d999b0a5,2019-02-16T01:02:32Z,2019-02-16T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,5103c940-0c08-392f-95cd-446e0cea042a,e2c226c2-3e1e-3d0b-b997-ce9544c10528,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,outpatient,185345009,Encounter for symptom,129.16,129.16,69.16,65363002.0,Otitis media
1,6a74fdef-2287-44bf-b9e7-18012376faca,2019-08-02T01:02:32Z,2019-08-02T01:32:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,0b9f3f7c-8ab6-30a5-b3ae-4dc0e0c00cb3,87c33fc5-3fd1-3c52-815a-b89a1623bb3a,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,129.16,129.16,NaN,NaN
2,8bca6d8a-ab80-4cbf-8abb-46654235f227,2019-10-31T01:02:32Z,2019-10-31T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,5103c940-0c08-392f-95cd-446e0cea042a,e2c226c2-3e1e-3d0b-b997-ce9544c10528,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,outpatient,185345009,Encounter for symptom,129.16,129.16,69.16,65363002.0,Otitis media
3,821e57ac-9304-46a9-9f9b-83daf60e9e43,2020-01-31T01:02:32Z,2020-01-31T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,0b9f3f7c-8ab6-30a5-b3ae-4dc0e0c00cb3,87c33fc5-3fd1-3c52-815a-b89a1623bb3a,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,129.16,129.16,NaN,NaN
4,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,fd328395-ab1d-35c6-a2d0-d05a9a79cf11,9c875a09-93e0-39aa-9260-ad264bbdd3fe,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,185345009,Encounter for symptom (procedure),129.16,129.16,69.16,NaN,NaN

In [5]:
# Let's remove the columns that we don't need
encounters_df = encounters_df.drop(columns=['ORGANIZATION', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE'])

# Change Description to Encounter_Description
encounters_df = encounters_df.rename(columns={'DESCRIPTION': 'ENCOUNTER_DESCRIPTION'})

encounters_df.head()

,Id,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION
0,d5ee30a9-362f-429e-a87a-ee38d999b0a5,2019-02-16T01:02:32Z,2019-02-16T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom,Otitis media
1,6a74fdef-2287-44bf-b9e7-18012376faca,2019-08-02T01:02:32Z,2019-08-02T01:32:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Well child visit (procedure),NaN
2,8bca6d8a-ab80-4cbf-8abb-46654235f227,2019-10-31T01:02:32Z,2019-10-31T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom,Otitis media
3,821e57ac-9304-46a9-9f9b-83daf60e9e43,2020-01-31T01:02:32Z,2020-01-31T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Well child visit (procedure),NaN
4,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN

In [6]:
# Number of unique enounters
print('The total number of unique encounters is: ', encounters_df['Id'].nunique())

The total number of unique encounters is:  321528

In [7]:
# Let's read the patients file
patients_df = pd.read_csv(r'10k_synthea_covid19_csv\10k_synthea_covid19_csv\patients.csv')

In [8]:
patients_df.head()

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,2017-08-24,NaN,999-68-6630,NaN,NaN,NaN,Jacinto644,Kris249,NaN,...,Beverly Massachusetts US,888 Hickle Ferry Suite 38,Springfield,Massachusetts,Hampden County,1106.0,42.151961,-72.598959,8446.49,1499.08
1,067318a4-db8f-447f-8b6e-f2f61e9baaa5,2016-08-01,NaN,999-15-5895,NaN,NaN,NaN,Alva958,Krajcik437,NaN,...,Boston Massachusetts US,1048 Skiles Trailer,Walpole,Massachusetts,Norfolk County,2081.0,42.177370,-71.281353,89893.40,1845.72
2,ae9efba3-ddc4-43f9-a781-f72019388548,1992-06-30,NaN,999-27-3385,S99971451,X53218815X,Mr.,Jayson808,Fadel536,NaN,...,Springfield Massachusetts US,1056 Harris Lane Suite 70,Chicopee,Massachusetts,Hampden County,1020.0,42.181642,-72.608842,577445.86,3528.84
3,199c586f-af16-4091-9998-ee4cfc02ee7a,2004-01-09,NaN,999-73-2461,S99956432,NaN,NaN,Jimmie93,Harris789,NaN,...,Worcester Massachusetts US,201 Mitchell Lodge Unit 67,Pembroke,Massachusetts,Plymouth County,NaN,42.075292,-70.757035,336701.72,2705.64
4,353016ea-a0ff-4154-85bb-1cf8b6cedf20,1996-11-15,NaN,999-60-7372,S99917327,X58903159X,Mr.,Gregorio366,Auer97,NaN,...,Patras Achaea GR,1050 Lindgren Extension Apt 38,Boston,Massachusetts,Suffolk County,2135.0,42.352434,-71.028610,484076.34,3043.04

In [9]:
# Let's remove the columns we don't need
patients_df = patients_df.drop(columns=['SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE'])

#change ID column to PATIENT
patients_df.rename(columns={'Id':'PATIENT'}, inplace=True)
patients_df.head()

,PATIENT,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER
0,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,2017-08-24,NaN,NaN,white,nonhispanic,M
1,067318a4-db8f-447f-8b6e-f2f61e9baaa5,2016-08-01,NaN,NaN,white,nonhispanic,F
2,ae9efba3-ddc4-43f9-a781-f72019388548,1992-06-30,NaN,S,white,nonhispanic,M
3,199c586f-af16-4091-9998-ee4cfc02ee7a,2004-01-09,NaN,NaN,white,nonhispanic,F
4,353016ea-a0ff-4154-85bb-1cf8b6cedf20,1996-11-15,NaN,NaN,white,nonhispanic,M

In [10]:
# Value count for unique patients
unique_patients = patients_df['PATIENT'].nunique()
print(f'The number of unique patients is {unique_patients}')

The number of unique patients is 12352

In [11]:
# Let's join the encounters and patients files at the Id column for patients and PATIENT column for encounters
merged_df = pd.merge(encounters_df, patients_df, on='PATIENT')
# Change Id column to ENCOUNTER
merged_df.rename(columns={'Id':'ENCOUNTER'}, inplace=True)
merged_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER
0,d5ee30a9-362f-429e-a87a-ee38d999b0a5,2019-02-16T01:02:32Z,2019-02-16T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom,Otitis media,2017-08-24,NaN,NaN,white,nonhispanic,M
1,6a74fdef-2287-44bf-b9e7-18012376faca,2019-08-02T01:02:32Z,2019-08-02T01:32:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Well child visit (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M
2,8bca6d8a-ab80-4cbf-8abb-46654235f227,2019-10-31T01:02:32Z,2019-10-31T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom,Otitis media,2017-08-24,NaN,NaN,white,nonhispanic,M
3,821e57ac-9304-46a9-9f9b-83daf60e9e43,2020-01-31T01:02:32Z,2020-01-31T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Well child visit (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M
4,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M

In [12]:
# Let's read the observations file

observations_df = pd.read_csv(r'10k_synthea_covid19_csv\10k_synthea_covid19_csv\observations.csv')

In [13]:
observations_df.head()

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,VALUE,UNITS,TYPE
0,2019-08-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,8302-2,Body Height,82.7,cm,numeric
1,2019-08-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,72514-3,Pain severity - 0-10 verbal numeric rating [Sc...,2.0,{score},numeric
2,2019-08-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,29463-7,Body Weight,12.6,kg,numeric
3,2019-08-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,77606-2,Weight-for-length Per age and sex,86.1,%,numeric
4,2019-08-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,9843-4,Head Occipital-frontal circumference,46.9,cm,numeric

In [14]:
# Let's remove the columns we don't need
observations_df = observations_df.drop(columns=['DATE', 'CODE', 'UNITS', 'TYPE'])

observations_df.head()

,PATIENT,ENCOUNTER,DESCRIPTION,VALUE
0,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,Body Height,82.7
1,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,Pain severity - 0-10 verbal numeric rating [Sc...,2.0
2,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,Body Weight,12.6
3,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,Weight-for-length Per age and sex,86.1
4,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,Head Occipital-frontal circumference,46.9

In [15]:
top_observations = observations_df['DESCRIPTION'].value_counts()
top_observations.head(10)

DESCRIPTION
Diastolic Blood Pressure                                               48132
Systolic Blood Pressure                                                48132
Body Weight                                                            46332
Heart rate                                                             46332
Respiratory rate                                                       46332
Oxygen saturation in Arterial blood                                    42995
Body temperature                                                       35639
Glomerular filtration rate/1.73 sq M.predicted                         26175
Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma    26147
Bilirubin.total [Mass/volume] in Serum or Plasma                       26147
Name: count, dtype: int64

In [16]:
# Let's keep only Diastolic Blood Pressure, Systolic Blood Pressure, Body Weight, Heart Rate, Respiratory Rate, Oxygen Saturation in Arterial Blood

observations_df = observations_df[observations_df['DESCRIPTION'].isin(['Diastolic Blood Pressure', 'Systolic Blood Pressure', 'Body Weight', 'Heart rate', 'Respiratory rate', 'Oxygen saturation in Arterial blood'])]

# Value counts for Description
print(observations_df['DESCRIPTION'].value_counts())

DESCRIPTION
Diastolic Blood Pressure               48132
Systolic Blood Pressure                48132
Body Weight                            46332
Heart rate                             46332
Respiratory rate                       46332
Oxygen saturation in Arterial blood    42995
Name: count, dtype: int64

In [17]:
#Let's create a pivot table with the desciption as columns and values as the values

pivot_table = observations_df.pivot_table(index=['PATIENT', 'ENCOUNTER'], columns='DESCRIPTION', values='VALUE', aggfunc='first').reset_index()

In [18]:
pivot_table.head()

DESCRIPTION,PATIENT,ENCOUNTER,Body Weight,Diastolic Blood Pressure,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,Systolic Blood Pressure
0,0000b247-1def-417a-a783-41c8682be022,93c3da2d-9420-49fa-94e3-7140ab9aeba1,38.5,83.0,127.0,81.5,33.7,108.0
1,0000b247-1def-417a-a783-41c8682be022,a5f3c5a7-fdf9-4bc5-94e2-4e93b11994cb,37.5,81.0,65.0,NaN,13.0,121.0
2,00049ee8-5953-4edd-a277-b9c1b1a7f16b,dab47020-5bd0-4ce6-ae5c-e4f1ebd04627,89.3,79.0,143.8,78.8,30.2,103.0
3,000769a6-23a7-426e-a264-cb0e509b2da2,247c24bc-258b-459c-a001-b911bd427f8d,73.3,84.0,77.0,NaN,15.0,106.0
4,00079a57-24a8-430f-b4f8-a1cf34f90060,2e72da06-9187-404d-85a4-fa5c0b68e86b,65.6,80.0,85.0,NaN,13.0,130.0

In [19]:
# Remove rows with missing values
pivot_table = pivot_table.dropna()

pivot_table.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11505 entries, 0 to 28306
Data columns (total 8 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   PATIENT                              11505 non-null  object
 1   ENCOUNTER                            11505 non-null  object
 2   Body Weight                          11505 non-null  object
 3   Diastolic Blood Pressure             11505 non-null  object
 4   Heart rate                           11505 non-null  object
 5   Oxygen saturation in Arterial blood  11505 non-null  object
 6   Respiratory rate                     11505 non-null  object
 7   Systolic Blood Pressure              11505 non-null  object
dtypes: object(8)
memory usage: 808.9+ KB

In [20]:
# Order the pivot table by date and patient
pivot_table = pivot_table.sort_values(by=['PATIENT', 'ENCOUNTER'])

In [21]:
# Merge the pivot table with the merged_df

final_df = pd.merge(merged_df, pivot_table, on=['PATIENT', 'ENCOUNTER'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,Body Weight,Diastolic Blood Pressure,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,Systolic Blood Pressure
0,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0
1,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,nonhispanic,F,15.8,79.0,172.4,79.3,20.0,118.0
2,eeab7c2d-71ba-4e04-af16-87a01dce7d54,2020-03-11T10:51:58Z,2020-03-11T11:42:58Z,ae9efba3-ddc4-43f9-a781-f72019388548,Encounter for symptom (procedure),NaN,1992-06-30,NaN,S,white,nonhispanic,M,68.2,96.0,186.9,88.7,32.5,187.0
3,8333efdf-f7bf-43bb-b73f-2b663d14c1ad,2020-03-02T04:15:46Z,2020-03-02T05:15:46Z,199c586f-af16-4091-9998-ee4cfc02ee7a,Encounter for symptom (procedure),NaN,2004-01-09,NaN,NaN,white,nonhispanic,F,45.3,89.0,97.5,78.2,22.3,120.0
4,8d502eec-afc0-4639-b298-a152a16d492a,2020-03-03T00:58:24Z,2020-03-03T02:19:24Z,353016ea-a0ff-4154-85bb-1cf8b6cedf20,Encounter for symptom (procedure),NaN,1996-11-15,NaN,NaN,white,nonhispanic,M,91.2,80.0,51.0,77.6,18.6,116.0

In [22]:
# Number of unique encounters
unique_encounters = final_df['ENCOUNTER'].nunique()
print(f'The number of unique encounters is {unique_encounters}')

The number of unique encounters is 11505

In [23]:
# Let's read the conditions file
conditions_df = pd.read_csv(r'10k_synthea_covid19_csv\10k_synthea_covid19_csv\conditions.csv')

In [24]:
conditions_df.head()

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION
0,2019-02-15,2019-08-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,d5ee30a9-362f-429e-a87a-ee38d999b0a5,65363002,Otitis media
1,2019-10-30,2020-01-30,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,8bca6d8a-ab80-4cbf-8abb-46654235f227,65363002,Otitis media
2,2020-03-01,2020-03-30,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,681c380b-3c84-4c55-80a6-db3d9ea12fee,386661006,Fever (finding)
3,2020-03-01,2020-03-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,681c380b-3c84-4c55-80a6-db3d9ea12fee,840544004,Suspected COVID-19
4,2020-03-01,2020-03-30,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,681c380b-3c84-4c55-80a6-db3d9ea12fee,840539006,COVID-19

In [25]:
# Remove columns that we don't need
conditions_df = conditions_df.drop(columns=['START', 'STOP', 'CODE'])

In [26]:
# Change the name of DESCRIPTION to CONDITION_DESCRIPTION
conditions_df = conditions_df.rename(columns={'DESCRIPTION': 'CONDITION_DESCRIPTION'})

# Merge the conditions_df with the final_df
final_df = pd.merge(final_df, conditions_df, on=['PATIENT', 'ENCOUNTER'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,Body Weight,Diastolic Blood Pressure,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,Systolic Blood Pressure,CONDITION_DESCRIPTION
0,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0,Fever (finding)
1,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0,Suspected COVID-19
2,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0,COVID-19
3,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,nonhispanic,F,15.8,79.0,172.4,79.3,20.0,118.0,Cough (finding)
4,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,nonhispanic,F,15.8,79.0,172.4,79.3,20.0,118.0,Sputum finding (finding)

In [27]:
# Create a new column that is a list of all the conditions for each unique encounter
final_df['CONDITIONS'] = final_df.groupby('ENCOUNTER')['CONDITION_DESCRIPTION'].transform(lambda x: ','.join(x))

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,Body Weight,Diastolic Blood Pressure,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,Systolic Blood Pressure,CONDITION_DESCRIPTION,CONDITIONS
0,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0,Fever (finding),"Fever (finding),Suspected COVID-19,COVID-19"
1,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0,Suspected COVID-19,"Fever (finding),Suspected COVID-19,COVID-19"
2,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0,COVID-19,"Fever (finding),Suspected COVID-19,COVID-19"
3,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,nonhispanic,F,15.8,79.0,172.4,79.3,20.0,118.0,Cough (finding),"Cough (finding),Sputum finding (finding),Diarr..."
4,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,nonhispanic,F,15.8,79.0,172.4,79.3,20.0,118.0,Sputum finding (finding),"Cough (finding),Sputum finding (finding),Diarr..."

In [28]:
# Number of unique encounters
unique_encounters = final_df['ENCOUNTER'].nunique()
print(f'The number of unique encounters is {unique_encounters}')

# Size of the final_df
print(f'The size of the final_df is {final_df.shape}')

The number of unique encounters is 11345
The size of the final_df is (64591, 20)

In [29]:
# Remove duplicate encounters
final_df = final_df.drop_duplicates(subset='ENCOUNTER')

# Remove the condition_description column
final_df = final_df.drop(columns=['CONDITION_DESCRIPTION'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,Body Weight,Diastolic Blood Pressure,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,Systolic Blood Pressure,CONDITIONS
0,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0,"Fever (finding),Suspected COVID-19,COVID-19"
3,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,nonhispanic,F,15.8,79.0,172.4,79.3,20.0,118.0,"Cough (finding),Sputum finding (finding),Diarr..."
9,eeab7c2d-71ba-4e04-af16-87a01dce7d54,2020-03-11T10:51:58Z,2020-03-11T11:42:58Z,ae9efba3-ddc4-43f9-a781-f72019388548,Encounter for symptom (procedure),NaN,1992-06-30,NaN,S,white,nonhispanic,M,68.2,96.0,186.9,88.7,32.5,187.0,"Headache (finding),Cough (finding),Fatigue (fi..."
18,8333efdf-f7bf-43bb-b73f-2b663d14c1ad,2020-03-02T04:15:46Z,2020-03-02T05:15:46Z,199c586f-af16-4091-9998-ee4cfc02ee7a,Encounter for symptom (procedure),NaN,2004-01-09,NaN,NaN,white,nonhispanic,F,45.3,89.0,97.5,78.2,22.3,120.0,"Cough (finding),Sputum finding (finding),Nause..."
25,8d502eec-afc0-4639-b298-a152a16d492a,2020-03-03T00:58:24Z,2020-03-03T02:19:24Z,353016ea-a0ff-4154-85bb-1cf8b6cedf20,Encounter for symptom (procedure),NaN,1996-11-15,NaN,NaN,white,nonhispanic,M,91.2,80.0,51.0,77.6,18.6,116.0,"Nasal congestion (finding),Cough (finding),Spu..."

In [30]:
# Size of the final_df
print(f'The size of the final_df is {final_df.shape}')

The size of the final_df is (11345, 19)

In [31]:
# Create a new column called AGE

import datetime

def calculate_age(birthdate, start):
    birthdate = datetime.datetime.strptime(birthdate, '%Y-%m-%d')
    start = datetime.datetime.strptime(start, '%Y-%m-%dT%H:%M:%SZ')
    age = start.year - birthdate.year - ((start.month, start.day) < (birthdate.month, birthdate.day))
    return age

final_df['AGE'] = final_df.apply(lambda x: calculate_age(x['BIRTHDATE'], x['START']), axis=1)

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,Body Weight,Diastolic Blood Pressure,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,Systolic Blood Pressure,CONDITIONS,AGE
0,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,nonhispanic,M,13.5,75.0,164.2,86.2,32.9,130.0,"Fever (finding),Suspected COVID-19,COVID-19",2
3,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,nonhispanic,F,15.8,79.0,172.4,79.3,20.0,118.0,"Cough (finding),Sputum finding (finding),Diarr...",3
9,eeab7c2d-71ba-4e04-af16-87a01dce7d54,2020-03-11T10:51:58Z,2020-03-11T11:42:58Z,ae9efba3-ddc4-43f9-a781-f72019388548,Encounter for symptom (procedure),NaN,1992-06-30,NaN,S,white,nonhispanic,M,68.2,96.0,186.9,88.7,32.5,187.0,"Headache (finding),Cough (finding),Fatigue (fi...",27
18,8333efdf-f7bf-43bb-b73f-2b663d14c1ad,2020-03-02T04:15:46Z,2020-03-02T05:15:46Z,199c586f-af16-4091-9998-ee4cfc02ee7a,Encounter for symptom (procedure),NaN,2004-01-09,NaN,NaN,white,nonhispanic,F,45.3,89.0,97.5,78.2,22.3,120.0,"Cough (finding),Sputum finding (finding),Nause...",16
25,8d502eec-afc0-4639-b298-a152a16d492a,2020-03-03T00:58:24Z,2020-03-03T02:19:24Z,353016ea-a0ff-4154-85bb-1cf8b6cedf20,Encounter for symptom (procedure),NaN,1996-11-15,NaN,NaN,white,nonhispanic,M,91.2,80.0,51.0,77.6,18.6,116.0,"Nasal congestion (finding),Cough (finding),Spu...",23

In [32]:
# Create a new column for death event
final_df['DEATH_EVENT'] = final_df['DEATHDATE'].notnull()

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,GENDER,Body Weight,Diastolic Blood Pressure,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,Systolic Blood Pressure,CONDITIONS,AGE,DEATH_EVENT
0,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,...,M,13.5,75.0,164.2,86.2,32.9,130.0,"Fever (finding),Suspected COVID-19,COVID-19",2,False
3,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,...,F,15.8,79.0,172.4,79.3,20.0,118.0,"Cough (finding),Sputum finding (finding),Diarr...",3,False
9,eeab7c2d-71ba-4e04-af16-87a01dce7d54,2020-03-11T10:51:58Z,2020-03-11T11:42:58Z,ae9efba3-ddc4-43f9-a781-f72019388548,Encounter for symptom (procedure),NaN,1992-06-30,NaN,S,white,...,M,68.2,96.0,186.9,88.7,32.5,187.0,"Headache (finding),Cough (finding),Fatigue (fi...",27,False
18,8333efdf-f7bf-43bb-b73f-2b663d14c1ad,2020-03-02T04:15:46Z,2020-03-02T05:15:46Z,199c586f-af16-4091-9998-ee4cfc02ee7a,Encounter for symptom (procedure),NaN,2004-01-09,NaN,NaN,white,...,F,45.3,89.0,97.5,78.2,22.3,120.0,"Cough (finding),Sputum finding (finding),Nause...",16,False
25,8d502eec-afc0-4639-b298-a152a16d492a,2020-03-03T00:58:24Z,2020-03-03T02:19:24Z,353016ea-a0ff-4154-85bb-1cf8b6cedf20,Encounter for symptom (procedure),NaN,1996-11-15,NaN,NaN,white,...,M,91.2,80.0,51.0,77.6,18.6,116.0,"Nasal congestion (finding),Cough (finding),Spu...",23,False

In [33]:
# Convert Systolic Blood Pressure and Diastolic Blood Pressure to float
final_df['Systolic Blood Pressure'] = final_df['Systolic Blood Pressure'].astype(float)
final_df['Diastolic Blood Pressure'] = final_df['Diastolic Blood Pressure'].astype(float)

# Create a new column for Mean Arterial Pressure (MAP)
final_df['MAP'] = final_df['Diastolic Blood Pressure'] + 1/3 * (final_df['Systolic Blood Pressure'] - final_df['Diastolic Blood Pressure'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,Body Weight,Diastolic Blood Pressure,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,Systolic Blood Pressure,CONDITIONS,AGE,DEATH_EVENT,MAP
0,681c380b-3c84-4c55-80a6-db3d9ea12fee,2020-03-02T01:02:32Z,2020-03-02T01:58:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,Encounter for symptom (procedure),NaN,2017-08-24,NaN,NaN,white,...,13.5,75.0,164.2,86.2,32.9,130.0,"Fever (finding),Suspected COVID-19,COVID-19",2,False,93.333333
3,1ea74a77-3ad3-4948-a9cc-3084462035d6,2020-03-13T08:02:25Z,2020-03-13T08:52:25Z,067318a4-db8f-447f-8b6e-f2f61e9baaa5,Encounter for symptom (procedure),NaN,2016-08-01,NaN,NaN,white,...,15.8,79.0,172.4,79.3,20.0,118.0,"Cough (finding),Sputum finding (finding),Diarr...",3,False,92.000000
9,eeab7c2d-71ba-4e04-af16-87a01dce7d54,2020-03-11T10:51:58Z,2020-03-11T11:42:58Z,ae9efba3-ddc4-43f9-a781-f72019388548,Encounter for symptom (procedure),NaN,1992-06-30,NaN,S,white,...,68.2,96.0,186.9,88.7,32.5,187.0,"Headache (finding),Cough (finding),Fatigue (fi...",27,False,126.333333
18,8333efdf-f7bf-43bb-b73f-2b663d14c1ad,2020-03-02T04:15:46Z,2020-03-02T05:15:46Z,199c586f-af16-4091-9998-ee4cfc02ee7a,Encounter for symptom (procedure),NaN,2004-01-09,NaN,NaN,white,...,45.3,89.0,97.5,78.2,22.3,120.0,"Cough (finding),Sputum finding (finding),Nause...",16,False,99.333333
25,8d502eec-afc0-4639-b298-a152a16d492a,2020-03-03T00:58:24Z,2020-03-03T02:19:24Z,353016ea-a0ff-4154-85bb-1cf8b6cedf20,Encounter for symptom (procedure),NaN,1996-11-15,NaN,NaN,white,...,91.2,80.0,51.0,77.6,18.6,116.0,"Nasal congestion (finding),Cough (finding),Spu...",23,False,92.000000

In [34]:
# Drop Sysolic Blood Pressure and Diastolic Blood Pressure
final_df = final_df.drop(columns=['Systolic Blood Pressure', 'Diastolic Blood Pressure'])

In [35]:
#Let's read the medications file
medications_df = pd.read_csv(r'10k_synthea_covid19_csv\10k_synthea_covid19_csv\medications.csv')

In [36]:
medications_df.head()

,START,STOP,PATIENT,PAYER,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION
0,2019-10-30,2019-11-13,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,8bca6d8a-ab80-4cbf-8abb-46654235f227,308182,Amoxicillin 250 MG Oral Capsule,7.05,0.0,1,7.05,NaN,NaN
1,2019-10-30,2019-11-13,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,8bca6d8a-ab80-4cbf-8abb-46654235f227,313820,Acetaminophen 160 MG Chewable Tablet,5.72,0.0,1,5.72,NaN,NaN
2,2020-02-12,2020-02-26,067318a4-db8f-447f-8b6e-f2f61e9baaa5,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,adedca64-700b-4fb9-82f1-9cbb658abb73,313820,Acetaminophen 160 MG Chewable Tablet,5.25,0.0,1,5.25,NaN,NaN
3,2020-04-28,2020-05-08,067318a4-db8f-447f-8b6e-f2f61e9baaa5,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,e03b96de-5604-4989-a2d5-03a63e041eab,834061,Penicillin V Potassium 250 MG Oral Tablet,13.90,0.0,1,13.90,43878008.0,Streptococcal sore throat (disorder)
4,2010-11-22,2011-08-30,ae9efba3-ddc4-43f9-a781-f72019388548,d47b3510-2895-3b70-9897-342d681c769d,11a2dfae-53d4-4d13-a74b-c540a525a1c4,999967,amLODIPine 5 MG / Hydrochlorothiazide 12.5 MG ...,263.49,0.0,9,2371.41,59621000.0,Hypertension

In [37]:
# Drop the columns we don't need
medications_df = medications_df.drop(columns=['START', 'STOP', 'PAYER', 'CODE', 'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE', 'REASONDESCRIPTION'])

medications_df.head()

,PATIENT,ENCOUNTER,DESCRIPTION
0,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,8bca6d8a-ab80-4cbf-8abb-46654235f227,Amoxicillin 250 MG Oral Capsule
1,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,8bca6d8a-ab80-4cbf-8abb-46654235f227,Acetaminophen 160 MG Chewable Tablet
2,067318a4-db8f-447f-8b6e-f2f61e9baaa5,adedca64-700b-4fb9-82f1-9cbb658abb73,Acetaminophen 160 MG Chewable Tablet
3,067318a4-db8f-447f-8b6e-f2f61e9baaa5,e03b96de-5604-4989-a2d5-03a63e041eab,Penicillin V Potassium 250 MG Oral Tablet
4,ae9efba3-ddc4-43f9-a781-f72019388548,11a2dfae-53d4-4d13-a74b-c540a525a1c4,amLODIPine 5 MG / Hydrochlorothiazide 12.5 MG ...

In [38]:
# merge the medications_df with the final_df
final_df = pd.merge(final_df, medications_df, on=['PATIENT', 'ENCOUNTER'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,GENDER,Body Weight,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,CONDITIONS,AGE,DEATH_EVENT,MAP,DESCRIPTION
0,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
1,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,NDA020503 200 ACTUAT Albuterol 0.09 MG/ACTUAT ...
2,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,Acetaminophen 500 MG Oral Tablet
3,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,1 ML Enoxaparin sodium 150 MG/ML Prefilled Syr...
4,b059d051-d157-4c83-be89-271808df2ebb,2020-03-07T13:00:03Z,2020-03-28T17:29:03Z,f39d31c4-9ba8-4468-9f48-065a8dc13e0f,Hospital admission for isolation (procedure),COVID-19,1983-09-30,NaN,M,white,...,F,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...

In [39]:
# Create a new column that is a list of all the medications for each unique encounter
final_df['MEDICATIONS'] = final_df.groupby('ENCOUNTER')['DESCRIPTION'].transform(lambda x: ','.join(x))

# Drop the description column
final_df = final_df.drop(columns=['DESCRIPTION'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,GENDER,Body Weight,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,CONDITIONS,AGE,DEATH_EVENT,MAP,MEDICATIONS
0,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
1,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
2,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
3,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
4,b059d051-d157-4c83-be89-271808df2ebb,2020-03-07T13:00:03Z,2020-03-28T17:29:03Z,f39d31c4-9ba8-4468-9f48-065a8dc13e0f,Hospital admission for isolation (procedure),COVID-19,1983-09-30,NaN,M,white,...,F,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...

In [40]:
# Drop duplicate encounters
final_df = final_df.drop_duplicates(subset='ENCOUNTER')

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,GENDER,Body Weight,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,CONDITIONS,AGE,DEATH_EVENT,MAP,MEDICATIONS
0,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
4,b059d051-d157-4c83-be89-271808df2ebb,2020-03-07T13:00:03Z,2020-03-28T17:29:03Z,f39d31c4-9ba8-4468-9f48-065a8dc13e0f,Hospital admission for isolation (procedure),COVID-19,1983-09-30,NaN,M,white,...,F,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
8,a8334fae-0b2c-465b-b162-af1442de4f67,2020-03-15T00:32:17Z,2020-04-02T06:25:17Z,da0334da-83d5-443c-9f80-185654a0c534,Hospital admission for isolation (procedure),COVID-19,1959-06-23,NaN,M,white,...,F,76.5,130.8,76.9,37.1,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",60,False,92.666667,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
10,6641f300-197a-4c00-8d01-5f6f8c1d45ca,2020-03-01T02:46:43Z,2020-03-07T04:59:43Z,b837f045-b9b5-486a-ad32-94b9f519737f,Hospital admission for isolation (procedure),COVID-19,1958-05-09,NaN,M,white,...,F,85.9,136.5,78.9,14.9,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",61,False,86.666667,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...
14,dc2cb1fd-e8fc-47fe-837c-4272c928c790,2020-03-10T04:42:36Z,2020-03-24T09:43:36Z,5b61f0fa-a3c4-4e70-a322-ad85c47aca12,Hospital admission for isolation (procedure),COVID-19,1987-08-31,NaN,M,white,...,M,87.7,194.2,86.9,24.2,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",32,False,88.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...

In [41]:
# Number of unique encounters
unique_encounters = final_df['ENCOUNTER'].nunique()
print(f'The number of unique encounters is {unique_encounters}')

The number of unique encounters is 2244

In [42]:
# Let's read the procedures file
procedures_df = pd.read_csv(r'10k_synthea_covid19_csv\10k_synthea_covid19_csv\procedures.csv')

In [43]:
procedures_df.head()

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2019-08-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,430193006,Medication Reconciliation (procedure),495.80,NaN,NaN
1,2020-03-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,681c380b-3c84-4c55-80a6-db3d9ea12fee,261352009,Face mask (physical object),516.65,840544004.0,Suspected COVID-19
2,2020-01-06,067318a4-db8f-447f-8b6e-f2f61e9baaa5,df2e9ebd-090c-4fb4-b749-ec6e4cf3e75e,430193006,Medication Reconciliation (procedure),453.37,NaN,NaN
3,2020-03-13,067318a4-db8f-447f-8b6e-f2f61e9baaa5,1ea74a77-3ad3-4948-a9cc-3084462035d6,261352009,Face mask (physical object),516.65,840544004.0,Suspected COVID-19
4,2020-04-28,067318a4-db8f-447f-8b6e-f2f61e9baaa5,e03b96de-5604-4989-a2d5-03a63e041eab,117015009,Throat culture (procedure),2169.16,43878008.0,Streptococcal sore throat (disorder)

In [44]:
# Let's drop the columns we don't need
procedures_df = procedures_df.drop(columns=['DATE', 'CODE', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION'])

procedures_df.head()

,PATIENT,ENCOUNTER,DESCRIPTION
0,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,6a74fdef-2287-44bf-b9e7-18012376faca,Medication Reconciliation (procedure)
1,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,681c380b-3c84-4c55-80a6-db3d9ea12fee,Face mask (physical object)
2,067318a4-db8f-447f-8b6e-f2f61e9baaa5,df2e9ebd-090c-4fb4-b749-ec6e4cf3e75e,Medication Reconciliation (procedure)
3,067318a4-db8f-447f-8b6e-f2f61e9baaa5,1ea74a77-3ad3-4948-a9cc-3084462035d6,Face mask (physical object)
4,067318a4-db8f-447f-8b6e-f2f61e9baaa5,e03b96de-5604-4989-a2d5-03a63e041eab,Throat culture (procedure)

In [45]:
# Merge the procedures_df with the final_df
final_df = pd.merge(final_df, procedures_df, on=['PATIENT', 'ENCOUNTER'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,Body Weight,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,CONDITIONS,AGE,DEATH_EVENT,MAP,MEDICATIONS,DESCRIPTION
0,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Plain chest X-ray (procedure)
1,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Oxygen administration by mask (procedure)
2,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Placing subject in prone position (procedure)
3,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Oxygen administration by mask (procedure)
4,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Placing subject in prone position (procedure)

In [46]:
# Delete duplicate encounters + procedures
final_df = final_df.drop_duplicates(subset=['ENCOUNTER', 'DESCRIPTION'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,Body Weight,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,CONDITIONS,AGE,DEATH_EVENT,MAP,MEDICATIONS,DESCRIPTION
0,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Plain chest X-ray (procedure)
1,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Oxygen administration by mask (procedure)
2,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Placing subject in prone position (procedure)
21,b059d051-d157-4c83-be89-271808df2ebb,2020-03-07T13:00:03Z,2020-03-28T17:29:03Z,f39d31c4-9ba8-4468-9f48-065a8dc13e0f,Hospital admission for isolation (procedure),COVID-19,1983-09-30,NaN,M,white,...,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Plain chest X-ray (procedure)
22,b059d051-d157-4c83-be89-271808df2ebb,2020-03-07T13:00:03Z,2020-03-28T17:29:03Z,f39d31c4-9ba8-4468-9f48-065a8dc13e0f,Hospital admission for isolation (procedure),COVID-19,1983-09-30,NaN,M,white,...,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,Oxygen administration by mask (procedure)

In [47]:
# Let's create a new column that is a list of all the procedures for each unique encounter
final_df['PROCEDURES'] = final_df.groupby('ENCOUNTER')['DESCRIPTION'].transform(lambda x: ','.join(x))

# Drop the description column
final_df = final_df.drop(columns=['DESCRIPTION'])

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,Body Weight,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,CONDITIONS,AGE,DEATH_EVENT,MAP,MEDICATIONS,PROCEDURES
0,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
1,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
2,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
21,b059d051-d157-4c83-be89-271808df2ebb,2020-03-07T13:00:03Z,2020-03-28T17:29:03Z,f39d31c4-9ba8-4468-9f48-065a8dc13e0f,Hospital admission for isolation (procedure),COVID-19,1983-09-30,NaN,M,white,...,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
22,b059d051-d157-4c83-be89-271808df2ebb,2020-03-07T13:00:03Z,2020-03-28T17:29:03Z,f39d31c4-9ba8-4468-9f48-065a8dc13e0f,Hospital admission for isolation (procedure),COVID-19,1983-09-30,NaN,M,white,...,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."

In [48]:
# Drop duplicate encounters
final_df = final_df.drop_duplicates(subset='ENCOUNTER')

final_df.head()

,ENCOUNTER,START,STOP,PATIENT,ENCOUNTER_DESCRIPTION,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,MARITAL,RACE,...,Body Weight,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,CONDITIONS,AGE,DEATH_EVENT,MAP,MEDICATIONS,PROCEDURES
0,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2020-02-19T05:30:14Z,2020-03-05T14:56:14Z,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,Hospital admission for isolation (procedure),COVID-19,2019-06-12,NaN,NaN,white,...,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
21,b059d051-d157-4c83-be89-271808df2ebb,2020-03-07T13:00:03Z,2020-03-28T17:29:03Z,f39d31c4-9ba8-4468-9f48-065a8dc13e0f,Hospital admission for isolation (procedure),COVID-19,1983-09-30,NaN,M,white,...,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
50,a8334fae-0b2c-465b-b162-af1442de4f67,2020-03-15T00:32:17Z,2020-04-02T06:25:17Z,da0334da-83d5-443c-9f80-185654a0c534,Hospital admission for isolation (procedure),COVID-19,1959-06-23,NaN,M,white,...,76.5,130.8,76.9,37.1,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",60,False,92.666667,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
79,6641f300-197a-4c00-8d01-5f6f8c1d45ca,2020-03-01T02:46:43Z,2020-03-07T04:59:43Z,b837f045-b9b5-486a-ad32-94b9f519737f,Hospital admission for isolation (procedure),COVID-19,1958-05-09,NaN,M,white,...,85.9,136.5,78.9,14.9,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",61,False,86.666667,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
99,dc2cb1fd-e8fc-47fe-837c-4272c928c790,2020-03-10T04:42:36Z,2020-03-24T09:43:36Z,5b61f0fa-a3c4-4e70-a322-ad85c47aca12,Hospital admission for isolation (procedure),COVID-19,1987-08-31,NaN,M,white,...,87.7,194.2,86.9,24.2,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",32,False,88.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."

In [49]:
# Number of unique encounters
unique_encounters = final_df['ENCOUNTER'].nunique()
print(f'The number of unique encounters is {unique_encounters}')

# Shape of the final_df
print(f'The size of the final_df is {final_df.shape}')

The number of unique encounters is 2244
The size of the final_df is (2244, 22)

In [50]:
# Remove columns that we don't need
final_df = final_df.drop(columns=['ENCOUNTER', 'START', 'STOP', 'PATIENT', 'ENCOUNTER_DESCRIPTION', 'REASONDESCRIPTION', 'BIRTHDATE', 'DEATHDATE', 'MARITAL'])

final_df.head()

,RACE,ETHNICITY,GENDER,Body Weight,Heart rate,Oxygen saturation in Arterial blood,Respiratory rate,CONDITIONS,AGE,DEATH_EVENT,MAP,MEDICATIONS,PROCEDURES
0,white,nonhispanic,F,8.3,136.5,78.6,14.0,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",0,False,93.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
21,white,nonhispanic,F,74.6,89.8,88.9,21.3,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",36,False,94.000000,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
50,white,nonhispanic,F,76.5,130.8,76.9,37.1,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",60,False,92.666667,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
79,white,nonhispanic,F,85.9,136.5,78.9,14.9,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",61,False,86.666667,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."
99,white,hispanic,M,87.7,194.2,86.9,24.2,"Pneumonia (disorder),Hypoxemia (disorder),Resp...",32,False,88.333333,0.4 ML Enoxaparin sodium 100 MG/ML Prefilled S...,"Plain chest X-ray (procedure),Oxygen administr..."

In [51]:
# Shape of the Final DataFrame
final_df.shape

(2244, 13)

In [52]:
# How many death events are in the final_df
deaths = final_df['DEATH_EVENT'].value_counts()
print('The number of death events is: ', deaths[True])

# What percentag of the final_df are death events
print('The percentage of death events is: ', f'{(deaths[True] / final_df.shape[0] * 100):.3f}%')

The number of death events is:  566
The percentage of death events is:  25.223%

In [53]:
import plotly.express as px

# Create a histogram for the age distribution of the patients
fig = px.histogram(final_df, x='AGE', color='DEATH_EVENT', title='Age Distribution of Patients', barmode='overlay')
fig.show()